#!/usr/bin/env python3
# config.py <paper.yaml> <output-config.mk>
# Reads the build: section of paper.yaml and writes a Makefile variable fragment
# to .tmp/config.mk, which the Makefile -includes so build settings live in one
# place (paper.yaml) rather than being split across paper.yaml and the Makefile.
#
# Supported build: fields → Makefile variables:
#   docx_template   → TEMPLATE
#   docx_method     → DOCX_METHOD
#   csl             → CSL
#   bib             → BIB
#   latex_template  → LATEX_TEMPLATE
#
# If a field is absent the variable is not written; the Makefile ?= defaults apply.

import sys
import yaml


FIELD_MAP = {
    "docx_template":  "TEMPLATE",
    "docx_method":    "DOCX_METHOD",
    "csl":            "CSL",
    "bib":            "BIB",
    "latex_template": "LATEX_TEMPLATE",
}


def main():
    if len(sys.argv) != 3:
        print("Usage: config.py <paper.yaml> <output-config.mk>", file=sys.stderr)
        sys.exit(1)

    yaml_path, output_path = sys.argv[1], sys.argv[2]

    with open(yaml_path) as f:
        meta = yaml.safe_load(f)

    build = meta.get("build", {}) or {}

    lines = ["# Generated by tools/config.py — do not edit manually\n"]
    for yaml_key, make_var in FIELD_MAP.items():
        value = build.get(yaml_key)
        if value is not None:
            lines.append(f"{make_var} := {value}\n")

    with open(output_path, "w") as f:
        f.writelines(lines)

    print(f"config: wrote {output_path}")


if __name__ == "__main__":
    main()
